name: parade-agent
version: 0.1.0.0

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleInstances
  - FunctionalDependencies
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - StandaloneDeriving
  - TypeSynonymInstances
  - ViewPatterns

library:
  source-dirs: src
  dependencies:
    - base
    - containers
    - elm-export
    - free
    - microlens-platform
    - MonadRandom
    - mtl
    - random-shuffle
    - template-haskell
    - unordered-containers
    - vector

executables:
  generate-elm-types:
    source-dirs: app
    main: GenerateElmTypes.hs
    dependencies:
      - base
      - containers
      - elm-export
      - parade-agent

tests:
  doctest:
    main: DocTest.hs
    source-dirs: test
    dependencies:
      - parade-agent
      - doctest

  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - parade-agent
      - hspec
