name: parade-agent
version: 0.1.0.0

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - LambdaCase
  - OverloadedStrings
  - ViewPatterns

dependencies:
  - base
  - vector
  - unordered-containers

library:
  source-dirs: src

tests:
  doctest:
    main: DocTest.hs
    source-dirs: test
    dependencies:
      - parade-agent
      - doctest

  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - parade-agent
      - hspec
