name: parade-agent
version: 0.1.0.0

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DeriveFunctor
  - FlexibleInstances
  - FunctionalDependencies
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base
  - containers
  - free
  - microlens-platform
  - MonadRandom
  - mtl
  - random-shuffle
  - template-haskell
  - unordered-containers
  - vector

library:
  source-dirs: src

tests:
  doctest:
    main: DocTest.hs
    source-dirs: test
    dependencies:
      - parade-agent
      - doctest

  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - parade-agent
      - hspec
